-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE "OverDose" (
    "ID" INTEGER   NOT NULL,
    "Date" date   NOT NULL,
    "DateType" varchar(25)   NOT NULL,
    "Age" int   NOT NULL,
    "Sex" varchar(10)   NOT NULL,
    "Race" varchar(50)   NOT NULL,
    "Ethnicity" varchar(100)   NOT NULL,
    "ResidenceCity" varchar(50)   NOT NULL,
    "ResidenceCounty" varchar(50)   NOT NULL,
    "ResidenceState" varchar(50)   NOT NULL,
    "InjuryCity" varchar(50)   NOT NULL,
    "InjuryCounty" varchar(50)   NOT NULL,
    "InjuryState" varchar(50)   NOT NULL,
    "InjuryPlace" varchar(150)   NOT NULL,
    "DescriptionofInjury" varchar(500)   NOT NULL,
    "DeathCity" varchar(50)   NOT NULL,
    "DeathCounty" varchar(50)   NOT NULL,
    "DeathState" varchar(50)   NOT NULL,
    "Location" varchar(200)   NOT NULL,
    "LocationifOther" varchar(200)   NOT NULL,
    "CauseofDeath" varchar(500)   NOT NULL,
    "MannerofDeath" varchar(50)   NOT NULL,
    "OtherSignificantConditions" varchar(100)   NOT NULL,
    "Heroin" varchar(5)   NOT NULL,
    "Heroindeathcertificate(DC)" varchar(5)   NOT NULL,
    "Cocaine" varchar(5)   NOT NULL,
    "Fentanyl" varchar(5)   NOT NULL,
    "FentanylAnalogue" varchar(5)   NOT NULL,
    "Oxycodone" varchar(5)   NOT NULL,
    "Oxymorphone" varchar(5)   NOT NULL,
    "Ethanol" varchar(5)   NOT NULL,
    "Hydrocodone" varchar(5)   NOT NULL,
    "Benzodiazepine" varchar(5)   NOT NULL,
    "Methadone" varchar(5)   NOT NULL,
    "Meth/Amphetamine" varchar(5)   NOT NULL,
    "Amphet" varchar(5)   NOT NULL,
    "Tramad" varchar(5)   NOT NULL,
    "Hydromorphone" varchar(5)   NOT NULL,
    "Morphine(NotHeroin)" varchar(25)   NOT NULL,
    "Xylazine" varchar(5)   NOT NULL,
    "Gabapentin" varchar(5)   NOT NULL,
    "OpiateNOS" varchar(5)   NOT NULL,
    "Heroin/Morph/Codeine" varchar(5)   NOT NULL,
    "OtherOpioid" varchar(50)   NOT NULL,
    "AnyOpioid" varchar(5)   NOT NULL,
    "Other" varchar(150)   NOT NULL,
    "DeathCityGeo" varchar(150)   NOT NULL,
    "latitude" varchar(20)   NOT NULL,
    "longitude" varchar(20)   NOT NULL,
    CONSTRAINT "pk_OverDose" PRIMARY KEY (
        "ID"
     )
);

